# Общая настройка

In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# Задание 1. Погрешности

Импорт экспериментальных данных

In [60]:
data_1 = pd.read_csv("experimental_data/task_01.csv", encoding='utf-8', index_col=0)
data_1 = data_1.reset_index(drop=True)
data_1

    h_mm   D_mm   d_mm
0  70.00  29.90  25.05
1  69.95  29.95  24.95
2  70.00  30.10  25.05
3  70.05  30.15  24.90
4  70.20  29.95  25.05
5    NaN  29.95  25.00
6    NaN    NaN  24.90
7    NaN    NaN  25.00

## Расчёт погрешности прямых измерений размеров цилиндра
Добавление комментариев к строке (измерение, среднее значение, погрешность и т. д.)

Расчёт среднего значения по формуле $$mean = \frac{\Sigma x}{n}$$ где $x$ - значение измерения, $n$ - количество измерений

In [61]:
data_1['Comment'] = [f'Measure {i}' for i in range(1, len(data_1) + 1)]

h_mean_mm = np.sum(data_1.iloc[:,0])/len(data_1)
D_mean_mm = np.sum(data_1.iloc[:,1])/len(data_1)
d_mean_mm = np.sum(data_1.iloc[:,2])/len(data_1)

data_1.loc[len(data_1)] = {
    'h_mm': np.round(h_mean_mm, 2),
    'D_mm': np.round(D_mean_mm, 2),
    'd_mm': np.round(d_mean_mm, 2),
    'Comment': 'Mean'
}

data_1

    h_mm   D_mm   d_mm    Comment
0  70.00  29.90  25.05  Measure 1
1  69.95  29.95  24.95  Measure 2
2  70.00  30.10  25.05  Measure 3
3  70.05  30.15  24.90  Measure 4
4  70.20  29.95  25.05  Measure 5
5    NaN  29.95  25.00  Measure 6
6    NaN    NaN  24.90  Measure 7
7    NaN    NaN  25.00  Measure 8
8  43.78  22.50  24.99       Mean

Расчёт погрешности округления по формуле $$\Delta x_{пр} = p \frac{h}{2}$$ где p - доверительная вероятность (0.95), h - половина цены деления шкалы прибора (0,05 мм)

In [62]:
p = 0.95
h_mm = 0.05

data_1.loc[len(data_1)] = {
    'h_mm': np.round(p*h_mm/2,2),
    'D_mm': np.round(p*h_mm/2,2),
    'd_mm': np.round(p*h_mm/2,2),
    'Comment': 'Round error'
}
data_1

    h_mm   D_mm   d_mm      Comment
0  70.00  29.90  25.05    Measure 1
1  69.95  29.95  24.95    Measure 2
2  70.00  30.10  25.05    Measure 3
3  70.05  30.15  24.90    Measure 4
4  70.20  29.95  25.05    Measure 5
5    NaN  29.95  25.00    Measure 6
6    NaN    NaN  24.90    Measure 7
7    NaN    NaN  25.00    Measure 8
8  43.78  22.50  24.99         Mean
9   0.02   0.02   0.02  Round error

Расчёт приборной погрешности по формуле: $$\Delta x_{пр} = \frac{2}{3}\delta x$$ где $\delta x$ - приборная погрешность нониусного штангенциркуля с ценой деления 0,05 мм (±0,05 мм)

In [63]:
delta_x_mm = 0.05

data_1.loc[len(data_1)] = {
    'h_mm': np.round(2/3*delta_x_mm,2),
    'D_mm': np.round(2/3*delta_x_mm,2),
    'd_mm': np.round(2/3*delta_x_mm,2),
    'Comment': 'Instrumental error'
}
data_1

     h_mm   D_mm   d_mm             Comment
0   70.00  29.90  25.05           Measure 1
1   69.95  29.95  24.95           Measure 2
2   70.00  30.10  25.05           Measure 3
3   70.05  30.15  24.90           Measure 4
4   70.20  29.95  25.05           Measure 5
5     NaN  29.95  25.00           Measure 6
6     NaN    NaN  24.90           Measure 7
7     NaN    NaN  25.00           Measure 8
8   43.78  22.50  24.99                Mean
9    0.02   0.02   0.02         Round error
10   0.03   0.03   0.03  Instrumental error

Количество измерений

In [64]:
h_nh_n = data_1['h_mm'].count()-3
D_n = data_1['D_mm'].count()-3
d_n = data_1['d_mm'].count()-3

data_1.loc[len(data_1)] = {
    'h_mm': h_n,
    'D_mm': D_n,
    'd_mm': d_n,
    'Comment': 'Number of measures'
}
data_1

     h_mm   D_mm   d_mm             Comment
0   70.00  29.90  25.05           Measure 1
1   69.95  29.95  24.95           Measure 2
2   70.00  30.10  25.05           Measure 3
3   70.05  30.15  24.90           Measure 4
4   70.20  29.95  25.05           Measure 5
5     NaN  29.95  25.00           Measure 6
6     NaN    NaN  24.90           Measure 7
7     NaN    NaN  25.00           Measure 8
8   43.78  22.50  24.99                Mean
9    0.02   0.02   0.02         Round error
10   0.03   0.03   0.03  Instrumental error
11   5.00   6.00   8.00  Number of measures

Точный расчёт коэффициента Стьюдента (через библиотеку SciPy)

In [65]:
t_h = np.round(stats.t.ppf(0.975, df=h_n-1),2)
t_D = np.round(stats.t.ppf(0.975, df=D_n-1),2)
t_d = np.round(stats.t.ppf(0.975, df=d_n-1),2)

data_1.loc[len(data_1)] = {
    'h_mm': t_h,
    'D_mm': t_D,
    'd_mm': t_d,
    'Comment': "Student's coefficient"
}
data_1

     h_mm   D_mm   d_mm                Comment
0   70.00  29.90  25.05              Measure 1
1   69.95  29.95  24.95              Measure 2
2   70.00  30.10  25.05              Measure 3
3   70.05  30.15  24.90              Measure 4
4   70.20  29.95  25.05              Measure 5
5     NaN  29.95  25.00              Measure 6
6     NaN    NaN  24.90              Measure 7
7     NaN    NaN  25.00              Measure 8
8   43.78  22.50  24.99                   Mean
9    0.02   0.02   0.02            Round error
10   0.03   0.03   0.03     Instrumental error
11   5.00   6.00   8.00     Number of measures
12   2.78   2.57   2.36  Student's coefficient

Расчёт случайной погрешности по формуле: $$\Delta x_{сл.} = t\sqrt\frac{\sum_{k=1}^{N}(x_k-\bar{x})^2}{N(N-1)}$$

In [66]:
data_1.loc[len(data_1)] = {
    'h_mm': np.round(t_h*np.sqrt(np.sum((data_1.iloc[:-5,0]-h_mean_mm)**2)/(h_n*(h_n - 1))), 2),
    'D_mm': np.round(t_D*np.sqrt(np.sum((data_1.iloc[:-5,1]-D_mean_mm)**2)/(D_n*(D_n - 1))), 2),
    'd_mm': np.round(t_d*np.sqrt(np.sum((data_1.iloc[:-5,2]-d_mean_mm)**2)/(d_n*(d_n - 1))), 2),
    'Comment': "Random error"
}
data_1

     h_mm   D_mm   d_mm                Comment
0   70.00  29.90  25.05              Measure 1
1   69.95  29.95  24.95              Measure 2
2   70.00  30.10  25.05              Measure 3
3   70.05  30.15  24.90              Measure 4
4   70.20  29.95  25.05              Measure 5
5     NaN  29.95  25.00              Measure 6
6     NaN    NaN  24.90              Measure 7
7     NaN    NaN  25.00              Measure 8
8   43.78  22.50  24.99                   Mean
9    0.02   0.02   0.02            Round error
10   0.03   0.03   0.03     Instrumental error
11   5.00   6.00   8.00     Number of measures
12   2.78   2.57   2.36  Student's coefficient
13  36.51   8.62   0.05           Random error

# Задание 2. Метод наименьших квадратов

In [67]:
data_2 = pd.read_csv("experimental_data/task_02.csv", encoding='utf-8', index_col=0)
data_2

       x      y
1    1.0  45.53
2    3.0  42.81
3    5.0  38.89
4    7.0  35.70
5    9.0  34.30
6   11.0  29.63
7   13.0  25.79
8   15.0  24.24
9   17.0  22.48
10  19.0  19.41

# Задание 3. МНК для нелинейной зависимости

In [68]:
data_3 = pd.read_csv("experimental_data/task_03.csv", encoding='utf-8', index_col=0)
data_3

       x       y
1    1.0   1.647
2    2.0   3.947
3    3.0   7.121
4    4.0  12.616
5    5.0  16.622
6    6.0  22.654
7    7.0  28.450
8    8.0  33.670
9    9.0  39.897
10  10.0  47.136